using UnityEngine;
using UnityEditor;
using System.IO;

public class rcProjectMenus
{
	static readonly string directoryForGeneratedFile = "/Scripts/Contrib/BigBit/Project/Editor/";

	[MenuItem("Scene Layers/Scenes/Regenerate Menu", false, 1000)]
	public static void Regenerate()
	{
		string generatedFile = "using UnityEngine;\nusing UnityEditor;\n\npublic class rcProjectMenus_AUTOGENERATED_\n{";


		string[] dirs = Directory.GetDirectories(Application.dataPath+"/Scenes");
		foreach(string dir in dirs)
		{
			string[] files = Directory.GetFiles(dir, "*_Map.unity");
			foreach(string file in files)
			{
				string fn = Path.GetFileNameWithoutExtension(file);
				fn = fn.Substring(0, fn.Length-4);

				generatedFile += string.Format("\n\n\t[MenuItem(\"Scene Layers/Scenes/{0}/Load\", false, 1)]\n\tstatic void Load_{0}() {{ rcMapLoadSave.LoadLevel(\"{0}\"); }}", fn);
				generatedFile += string.Format("\n\n\t[MenuItem(\"Scene Layers/Scenes/{0}/Bake\", false, 1)]\n\tstatic void Bake_{0}() {{ rcMapLoadSave.BakeLevel(\"{0}\"); }}", fn);
			}
		}

		generatedFile += "\n}";

		Debug.Log(generatedFile);
		
		using (StreamWriter sw = File.CreateText(Application.dataPath + directoryForGeneratedFile + "rcProjectMenus_AUTOGENERATED_.cs"))
		{
			sw.Write(generatedFile);
		}
		AssetDatabase.Refresh();
	}
}
